remote_theme: pmarsceill/just-the-docs
theme: "just-the-docs"
title: "VAE"

search_enabled: true

# Set the search token separator
search_tokenizer_separator: /[\s/]+/

aux_links:
    "Source code on Github":
      - "//github.com/elijahc/vae"
    "Preprint on BioArXiv":
      - "https://www.biorxiv.org/content/10.1101/2020.02.21.958488v1.full"

exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]


heading_anchors: true
